package il.org.spartan.Leonidas.plugin.GUI.About;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import il.org.spartan.Leonidas.plugin.GUI.LeonidasIcon;

import javax.swing.*;
import java.awt.*;


/**
 * @author Amir Sagiv
 * @since 28/04/2017
 */
class AboutLeonidas extends JFrame {
    private JPanel panel1;
    private JTextPane textPane1;
    private JButton closeButton;

    public AboutLeonidas() {
        super("About Leonidas Plugin");
        LeonidasIcon.apply(this);
        setContentPane(panel1);
        setPreferredSize(new Dimension(1000, 600));
        setResizable(false);
        pack();
        setVisible(true);
        closeButton.addActionListener(e -> closeButtonListener());
        textPane1.setFont(textPane1.getFont().deriveFont(16f));
        textPane1.setText("Welcome to IntelliJ Leonidas Plugin.\n\n" +
                "This Plugin was originally developed by 7 students from the Israeli institute of technology - The Technion.\n" +
                "The plugin offers you a tool to apply the principles of Spartan Programming to your Java code.\n" +
                "It applies many different tippers, which are little rules that provide suggestions on how to shorten and simplify your code,e.g, by using fewer variables, factoring out common structures, more efficient use of control flow, etc.\n" +
                "\nThe plugin will help you make a sequence small, nano-refactorings of your code, to make it shorter, and more conforming to a language of nano-patterns.\n" +
                "The resulting code is not just shorter, it is more regular. The spartanization process tries to remove as many distracting details and variations from the code,\n" +
                "stripping it to its bare bone.\n\n" +
                "The plugin is based on the PSI library of IntelliJ-IDEA that allowed us to analyze java code by creating Abstract Syntax Trees from existing code and make changes in these trees.\n" +
                "Each tipper in this plugin was written in a language that we all designed called - Leonidas.\n" +
                "Using this language we are able to create code transformations only by writing an example of generic code that represents the 'before' and 'after' states of these transformation" +
                "\n\n" +
                "In addition to the tipping mechanism, We offer you to enjoy our user services which can be found under 'Leonidas' section in the menu bar of IntelliJ.\n" +
                "There are currently 3 services available:\n" +
                "(1) ToolBox Controller - Decide the tippers you want to be notified about.\n" +
                "(2) Playground - experience the Spartanizer tippers in an isolated environment without effecting your code.\n" +
                "(3) Tipper creator - easily create new tippers by code examples without knowing Leonidas language at all!" +
                "\n\nWe encourage you all to join us in developing and enjoying the power of our plugin and the Leonidas language.\n\n" +
                "Leonidas Team.");
    }

    private void closeButtonListener() {
        this.dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel2.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        textPane1 = new JTextPane();
        textPane1.setEditable(false);
        textPane1.setText("");
        scrollPane1.setViewportView(textPane1);
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, 1, new Dimension(40, 40), new Dimension(10, 10), new Dimension(10, 10), 0, false));
        final Spacer spacer2 = new Spacer();
        panel1.add(spacer2, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, 1, new Dimension(40, 40), new Dimension(10, 10), new Dimension(10, 10), 1, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(20, 20, 20, 0), -1, -1));
        panel1.add(panel3, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_SOUTHEAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        closeButton = new JButton();
        closeButton.setText("Close");
        panel3.add(closeButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        panel1.add(panel4, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
